# NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [18]:
import numpy as np

In [19]:
lista = [1, 2, 3]

In [20]:
type(lista)

list

In [21]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

numpy.ndarray

#### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [6]:
vector = [-2, 4, 1, 3.5]

vector = np.array(vector)

vector

array([-2. ,  4. ,  1. ,  3.5])

In [7]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

0
1


In [8]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

[-2.   2.   3.   6.5]
[ -2.  -8.  -8. -28.]


In [9]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(2, 2)

matriz_1

array([[-2. ,  4. ],
       [ 1. ,  3.5]])

In [10]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .T

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[-2.   1. ]
 [ 4.   3.5]]
--------------------
[[-2.   1. ]
 [ 4.   3.5]]


In [11]:
# .tolist() retorna el array en una lista

vector.tolist()

[-2.0, 4.0, 1.0, 3.5]

In [12]:
# .flatten() retorna un vector plano con los elementos de la matriz

matriz_1.flatten()

array([-2. ,  4. ,  1. ,  3.5])

In [13]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

print("Antes de .sort()", vector)

vector.sort()

print("Después de .sort()", vector)

Antes de .sort() [-2.   4.   1.   3.5]
Después de .sort() [-2.   1.   3.5  4. ]


In [14]:
# .ndim retorna el número de dimensiones

vector.ndim

1

In [15]:
# .size retorna el número de elementos

vector.size

4

In [16]:
# .shape retorna en una tupla las dimesiones de la matriz

vector.shape

(4,)

In [17]:
# .dtype retorna el tipo de dato de los elementos de la matriz

vector.dtype

dtype('float64')

#### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [31]:
matriz = np.array([[1, 2, 3, 10], [4, 5, 6, 20], [7, 8, 9, 30]])

matriz

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [34]:
print(matriz)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [ ]:
matriz.flatten()

In [ ]:
matriz.reshape(4, 3)

In [ ]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty((5, 5), dtype = "int8")

print(empty)

In [ ]:
# Inicializa una matriz de 1's.

ones = np.ones((5, 5))

print(ones)

In [ ]:
# Inicializa una matriz de 0's.

zeros = np.zeros((5, 5))

print(zeros)

In [ ]:
# Matriz identidad

np.eye(5)

In [30]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full((5, 5), range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [29]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(1, 12, 16)

print(linspace)

[ 1.          1.73333333  2.46666667  3.2         3.93333333  4.66666667
  5.4         6.13333333  6.86666667  7.6         8.33333333  9.06666667
  9.8        10.53333333 11.26666667 12.        ]


## Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [41]:
matriz = np.array([[1, 0, 0, 0, 0], [0, 0, 2, 0, 0], [1, 1, 0, 0, 1], [2, 1, 1, 1, 0], [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [42]:
# Hacer

matriz[4][1]

2

In [43]:
# Es igual que hacer

matriz[4, 1]

2

In [44]:
# Slicing
matriz[1:4, 1:4]

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [45]:
# Slicing + Indexing

matriz[[1, 3], [2, 4]]

array([2, 0])

## Operaciones con Arrays

In [ ]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

In [ ]:
# Suma

A + B

In [ ]:
# Resta
A - B

In [ ]:
# Multiplicación por escalar

A * 5

In [ ]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

In [ ]:
# División por escalar

A / 5

In [ ]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

#### Concatenar

In [ ]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0)

In [ ]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1)

## Número aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                                                                                 |
|**`np.random.RandomState(n)`**      | Genera una semilla.                                                                                                                                 |

In [46]:
print(np.random.random())

print("-"*30)

print(np.random.random(5))

0.07635176735080995
------------------------------
[0.99743769 0.58741242 0.01375774 0.54328413 0.7149388 ]


In [47]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(2, 3))

0.32555130149085987
------------------------------
[[0.3303376  0.31775599 0.79219117]
 [0.82354719 0.99316075 0.17764471]]


In [ ]:
print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

In [ ]:
print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = [5]))

In [ ]:
print(np.random.choice(["a", "e", "i", "o", "u"], size = 10, p = [0.6, 0.1, 0.1, 0.1, 0.1])) 

In [ ]:
for i in range(5):
    np.random.seed(4)
    print(np.random.randn())

In [ ]:
for i in range(4):
    rs = np.random.RandomState(2)
    print(rs.rand())
    print(rs.randint(0, 10))
    print(np.random.randn()) # No usa rs
    print("-"*30)    

In [ ]:
np.random.seed(15)

for i in range(4):
    print(np.random.rand())
    print(np.random.randint(0, 10))
    print(np.random.randn())
    print("-"*30)  

In [ ]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

np.set_printoptions(formatter = {"float": lambda x: "{0:0.2f}".format(x)})

np.random.randn(6, 6)

In [ ]:
################################################################################################################################